"""Pre-built board templates for common PM flows."""

TEMPLATES = {
    'sprint_planning': {
        'name': 'Sprint Planning Flow',
        'type': 'process_flow',
        'description': 'Standard sprint planning workflow from backlog grooming to sprint review',
        'nodes': [
            {'label': 'Backlog Grooming', 'node_type': 'start', 'x': 80, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'Sprint Planning Meeting', 'node_type': 'process', 'x': 340, 'y': 200, 'width': 200, 'height': 60},
            {'label': 'Capacity Check', 'node_type': 'decision', 'x': 620, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Assign Tasks', 'node_type': 'process', 'x': 860, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Re-scope Sprint', 'node_type': 'process', 'x': 860, 'y': 300, 'width': 160, 'height': 60},
            {'label': 'Daily Standups', 'node_type': 'process', 'x': 1100, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Sprint Review', 'node_type': 'process', 'x': 1340, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Retrospective', 'node_type': 'end', 'x': 1580, 'y': 200, 'width': 160, 'height': 60},
        ],
        'edges': [
            {'from_index': 0, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 1, 'to_index': 2, 'label': '', 'edge_type': 'default'},
            {'from_index': 2, 'to_index': 3, 'label': 'Yes', 'edge_type': 'success'},
            {'from_index': 2, 'to_index': 4, 'label': 'No', 'edge_type': 'failure'},
            {'from_index': 3, 'to_index': 5, 'label': '', 'edge_type': 'default'},
            {'from_index': 4, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 5, 'to_index': 6, 'label': '', 'edge_type': 'default'},
            {'from_index': 6, 'to_index': 7, 'label': '', 'edge_type': 'default'},
        ],
    },
    'release_pipeline': {
        'name': 'Release Pipeline',
        'type': 'process_flow',
        'description': 'CI/CD release pipeline from feature branch to production deploy',
        'nodes': [
            {'label': 'Feature Branch', 'node_type': 'start', 'x': 80, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Code Review', 'node_type': 'process', 'x': 320, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Review Approved?', 'node_type': 'decision', 'x': 560, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'CI Build & Test', 'node_type': 'process', 'x': 820, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Fix Issues', 'node_type': 'process', 'x': 820, 'y': 300, 'width': 160, 'height': 60},
            {'label': 'Tests Pass?', 'node_type': 'decision', 'x': 1060, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Stage Deploy', 'node_type': 'process', 'x': 1300, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'QA Sign-off', 'node_type': 'decision', 'x': 1540, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Prod Deploy', 'node_type': 'end', 'x': 1780, 'y': 120, 'width': 160, 'height': 60},
        ],
        'edges': [
            {'from_index': 0, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 1, 'to_index': 2, 'label': '', 'edge_type': 'default'},
            {'from_index': 2, 'to_index': 3, 'label': 'Approved', 'edge_type': 'success'},
            {'from_index': 2, 'to_index': 4, 'label': 'Changes', 'edge_type': 'failure'},
            {'from_index': 4, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 3, 'to_index': 5, 'label': '', 'edge_type': 'default'},
            {'from_index': 5, 'to_index': 6, 'label': 'Pass', 'edge_type': 'success'},
            {'from_index': 5, 'to_index': 4, 'label': 'Fail', 'edge_type': 'failure'},
            {'from_index': 6, 'to_index': 7, 'label': '', 'edge_type': 'default'},
            {'from_index': 7, 'to_index': 8, 'label': 'Approved', 'edge_type': 'success'},
            {'from_index': 7, 'to_index': 4, 'label': 'Issues', 'edge_type': 'failure'},
        ],
    },
    'bug_triage': {
        'name': 'Bug Triage Process',
        'type': 'process_flow',
        'description': 'Bug report triage from submission to resolution',
        'nodes': [
            {'label': 'Bug Reported', 'node_type': 'start', 'x': 80, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Triage Review', 'node_type': 'process', 'x': 320, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Valid Bug?', 'node_type': 'decision', 'x': 560, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Prioritize', 'node_type': 'process', 'x': 800, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Close as Invalid', 'node_type': 'end', 'x': 800, 'y': 300, 'width': 160, 'height': 60},
            {'label': 'Assign Developer', 'node_type': 'process', 'x': 1040, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Fix & PR', 'node_type': 'process', 'x': 1280, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Verify Fix', 'node_type': 'decision', 'x': 1520, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Resolved', 'node_type': 'end', 'x': 1760, 'y': 120, 'width': 160, 'height': 60},
        ],
        'edges': [
            {'from_index': 0, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 1, 'to_index': 2, 'label': '', 'edge_type': 'default'},
            {'from_index': 2, 'to_index': 3, 'label': 'Yes', 'edge_type': 'success'},
            {'from_index': 2, 'to_index': 4, 'label': 'No', 'edge_type': 'failure'},
            {'from_index': 3, 'to_index': 5, 'label': '', 'edge_type': 'default'},
            {'from_index': 5, 'to_index': 6, 'label': '', 'edge_type': 'default'},
            {'from_index': 6, 'to_index': 7, 'label': '', 'edge_type': 'default'},
            {'from_index': 7, 'to_index': 8, 'label': 'Fixed', 'edge_type': 'success'},
            {'from_index': 7, 'to_index': 6, 'label': 'Not fixed', 'edge_type': 'failure'},
        ],
    },
    'feature_request': {
        'name': 'Feature Request Lifecycle',
        'type': 'process_flow',
        'description': 'Feature request from proposal to delivery',
        'nodes': [
            {'label': 'Feature Proposed', 'node_type': 'start', 'x': 80, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'Initial Review', 'node_type': 'process', 'x': 340, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Feasibility?', 'node_type': 'decision', 'x': 580, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Design & Spec', 'node_type': 'process', 'x': 820, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Defer / Reject', 'node_type': 'end', 'x': 820, 'y': 310, 'width': 160, 'height': 60},
            {'label': 'Development', 'node_type': 'process', 'x': 1060, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Testing', 'node_type': 'process', 'x': 1300, 'y': 120, 'width': 160, 'height': 60},
            {'label': 'Ship It', 'node_type': 'end', 'x': 1540, 'y': 120, 'width': 160, 'height': 60},
        ],
        'edges': [
            {'from_index': 0, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 1, 'to_index': 2, 'label': '', 'edge_type': 'default'},
            {'from_index': 2, 'to_index': 3, 'label': 'Feasible', 'edge_type': 'success'},
            {'from_index': 2, 'to_index': 4, 'label': 'Not now', 'edge_type': 'failure'},
            {'from_index': 3, 'to_index': 5, 'label': '', 'edge_type': 'default'},
            {'from_index': 5, 'to_index': 6, 'label': '', 'edge_type': 'default'},
            {'from_index': 6, 'to_index': 7, 'label': '', 'edge_type': 'default'},
        ],
    },
    'onboarding': {
        'name': 'Onboarding Workflow',
        'type': 'process_flow',
        'description': 'New employee onboarding process flow',
        'nodes': [
            {'label': 'Offer Accepted', 'node_type': 'start', 'x': 80, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Prep Accounts', 'node_type': 'process', 'x': 320, 'y': 200, 'width': 160, 'height': 60},
            {'label': 'Day 1 Orientation', 'node_type': 'process', 'x': 560, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'Team Introduction', 'node_type': 'process', 'x': 820, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'Training Plan', 'node_type': 'process', 'x': 1080, 'y': 200, 'width': 160, 'height': 60},
            {'label': '30-day Check-in', 'node_type': 'decision', 'x': 1320, 'y': 200, 'width': 180, 'height': 60},
            {'label': 'Fully Onboarded', 'node_type': 'end', 'x': 1580, 'y': 120, 'width': 180, 'height': 60},
            {'label': 'Extend Training', 'node_type': 'process', 'x': 1580, 'y': 300, 'width': 180, 'height': 60},
        ],
        'edges': [
            {'from_index': 0, 'to_index': 1, 'label': '', 'edge_type': 'default'},
            {'from_index': 1, 'to_index': 2, 'label': '', 'edge_type': 'default'},
            {'from_index': 2, 'to_index': 3, 'label': '', 'edge_type': 'default'},
            {'from_index': 3, 'to_index': 4, 'label': '', 'edge_type': 'default'},
            {'from_index': 4, 'to_index': 5, 'label': '', 'edge_type': 'default'},
            {'from_index': 5, 'to_index': 6, 'label': 'Ready', 'edge_type': 'success'},
            {'from_index': 5, 'to_index': 7, 'label': 'Needs more', 'edge_type': 'failure'},
            {'from_index': 7, 'to_index': 5, 'label': '', 'edge_type': 'default'},
        ],
    },
}
